# Numpy Guide for People In a Hurry

In [1]:
import numpy as np

## Multiple Ways to Create Numpy Arrays

In [18]:
array0 = np.array([0, 1, 2, 3, 4, 5]) #1 dimensional array
array0

array([0, 1, 2, 3, 4, 5])

In [3]:
array1 = np.array([[0, 1, 2], [ 3, 4, 5]]) #2 dimensional array
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
array2 = np.array(range(10)) #array with numbers 0 to 9
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array3 = np.zeros((4,3)) #array of zeroes 4 rows long by 3 columns wide
array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array4 = np.ones((2,2)) #array of ones 2 rows long by 2 columns wide
array4

array([[1., 1.],
       [1., 1.]])

In [7]:
array5 = np.identity(3) #identity matrix with dimension of 3
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
lst = [0, 1, 2, 3, 4]
numpy_lst = np.array(lst) #turn a list into a numpy array
numpy_lst

array([0, 1, 2, 3, 4])

## Accessing Elements In Array

In [22]:
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
array1[0,0] #access row index 0, column index 0 

0

In [25]:
array1[1,2] #access row index 1, column index 2

5

In [28]:
array1[0,2] #access row index 0, column index 2

2

In [29]:
array1[0:2,0:2] #access a slice of the array

array([[0, 1],
       [3, 4]])

## Broadcasting

In [58]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [59]:
x.shape #returns the shape or dimensions of the array

(6,)

In [60]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [61]:
y.shape

(5,)

In [62]:
x + y

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [64]:
xx = x.reshape(6,1)
xx

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.]])

## Useful for Python Coding Puzzles

## Mathematical Calculations and Other Matrix Operations

In [77]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr1 + arr2 #sum of arr1 and arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [80]:
arr1 + 1 #add 1 to every element in the array

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [81]:
np.sum(arr1) #sum of all elements within the arr1 array

9.0

In [82]:
(arr1 + 1) * arr2 #multiplication of 2 arrays

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.]])

In [83]:
np.dot(arr1, arr2) #dot product of 2 arrays

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [86]:
np.concatenate((arr1, arr2), axis=0) #concatenate by rows

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [87]:
np.concatenate((arr1, arr2), axis=1) #concatenate by columns

array([[1., 1., 1., 0., 1., 2.],
       [1., 1., 1., 3., 4., 5.],
       [1., 1., 1., 6., 7., 8.]])

In [5]:
np.split(arr2,3) #split the array into 3 arrays

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [14]:
np.hsplit(arr2,3) #split the array horizontally

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [15]:
np.delete(arr2,2,axis=0) #delete row index 2

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.delete(arr2,2,axis=1) #delete column index 2

array([[0, 1],
       [3, 4],
       [6, 7]])

In [88]:
np.transpose(arr2) #transpose the array

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [89]:
arr2.diagonal() #get only diagonal elements of the numpy array

array([0, 4, 8])

## Comparisons and Masks

### Example 1: Return only elements greater than 2

In [100]:
array0

array([[0, 1, 2, 3, 4, 5]])

In [101]:
array0 > 2 #returns boolean array

array([[False, False, False,  True,  True,  True]])

In [102]:
mask = array0 > 2
array0[mask]

array([3, 4, 5])

### Example 2: Return only elements greater than 4 or less than 2.

In [45]:
array0

array([0, 1, 2, 3, 4, 5])

In [46]:
mask = (array0 > 4) | (array0 < 2)

In [47]:
array0[mask]

array([0, 1, 5])